# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Business-AU-ABN
version:      0.4
version_from: lib/Business/AU/ABN.pm
installdirs:  site
requires:
    File::Spec:                    0.83
    List::Util:                    1.11
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.16
