---
abstract: 'Validate and format Australian Business Numbers'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  File::Spec: 0.80
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Business::AU::ABN
name: Business-AU-ABN
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  List::Util: 1.11
  Params::Util: 0.25
  perl: 5.005
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/Business-AU-ABN
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Business-AU-ABN
version: 1.09
