---
abstract: 'Validate and format Australian Business Numbers'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  File::Spec: 0.80
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Business::AU::ABN
name: Business-AU-ABN
no_index:
  directory:
    - inc
    - t
requires:
  Exporter: 0
  List::Util: 1.11
  Params::Util: 0.25
  constant: 0
  overload: 0
  perl: 5.005
resources:
  license: http://dev.perl.org/licenses/
version: 1.08
